CREATE TABLE projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    image TEXT,
    description TEXT,
    gift_recipient TEXT,
    gift_occasion TEXT,
    yarn TEXT,
    needles TEXT,
    pattern_id INTEGER REFERENCES patterns(id),
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);